In [1]:
import numpy as np
import pandas as pd
count =0
df = pd.DataFrame(columns=['A','B','C','F(A)','F(B)','F(B)','Error'])

def bisection(num1,num2):
    return (num1+num2)/2

def equation(x):
    return (x**2)-3

Tresh = float(input("Enter Error: "))
while True:
    a = float(input("Enter A Value: "))
    b = float(input("Enter B Value: "))
    ffa = equation(a)
    ffb = equation(b)
    if ((ffa*ffb)>0):
        print("Intermediate Theoram could apply because one of the function of value should return positive and other negative")
    else:
        break

while True:
    c = bisection(a,b)
    df.loc[count] = [a,b,c,equation(a),equation(b),equation(c),(c-a)]
    if (equation(c) * equation(a))>0:
        a = c
    else:
        b = c
    count = count+1
    if np.abs(float(a-b)) <= Tresh:
        break
        
df

Enter Error: 0.001
Enter A Value: 2
Enter B Value: 4
Intermediate Theoram could apply because one of the function of value should return positive and other negative
Enter A Value: 1
Enter B Value: 2

          A         B         C      F(A)      F(B)      F(B)     Error
0  1.000000  2.000000  1.500000 -2.000000  1.000000 -0.750000  0.500000
1  1.500000  2.000000  1.750000 -0.750000  1.000000  0.062500  0.250000
2  1.500000  1.750000  1.625000 -0.750000  0.062500 -0.359375  0.125000
3  1.625000  1.750000  1.687500 -0.359375  0.062500 -0.152344  0.062500
4  1.687500  1.750000  1.718750 -0.152344  0.062500 -0.045898  0.031250
5  1.718750  1.750000  1.734375 -0.045898  0.062500  0.008057  0.015625
6  1.718750  1.734375  1.726562 -0.045898  0.008057 -0.018982  0.007812
7  1.726562  1.734375  1.730469 -0.018982  0.008057 -0.005478  0.003906
8  1.730469  1.734375  1.732422 -0.005478  0.008057  0.001286  0.001953
9  1.730469  1.732422  1.731445 -0.005478  0.001286 -0.002097  0.000977